apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager-rollout.fullname" . }}
  labels:
    {{- include "manager-rollout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: manager-demo
