# Default values for manager-rollout.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

namespace: "manager-rollout"

image:
  repository: "asia-northeast3-docker.pkg.dev/jieum-dev/jongsoo/manager" # GKE artifact registry
#  repository: "jongsoo/manager" # DockerHub
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.0"

service:
  type: LoadBalancer
  port: 80
