apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: {{ .Values.name }}-canary
      stableService: {{ .Values.name }}-stable
      trafficRouting:
        alb:
          ingress: {{ .Values.name }}-ingress
          servicePort: 80
          rootService: {{ .Values.name }}-root
      steps:
        - setWeight: 5
        - pause: {duration: 3m}
        - setWeight: 30
        - pause: {duration: 3m}
        - setWeight: 50
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m