apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.name }}
  http:
    - name: primary
      route:
        - destination:
            host: {{ .Values.name }}-stable
            port:
              number: 5000
          weight: 100
        - destination:
            host: {{ .Values.name }}-canary
            port:
              number: 5000
          weight: 0